graphql:
  packages: com.tav.reactive

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres@localhost:5432/reactive
    password: postgres

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG